# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eddf6b39d8af74d5a9b1d80615d7ed6da6c52b4b0beed550cc89bf1a5324a08c86a0dcbd5661b14cd854468e788608969694e6456b7d378a15425c263b2a23f3

test:
  secret_key_base: 7212f69878b16ee7fecb886ed67187372a9567b7a2289fe37e69dccb2200553992f0ed3507d48400a5e22764ed9c9765016243fa3a3d30392bf778663143c8f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
